#!/bin/sh

files=$(git diff --cached --name-status)

for file in $files; do
	if [ "${file##*.}" = "pkl" ]; then
		pkl eval "$file" -o "${file%.pkl}.generated.yml"
		git add "${file%.pkl}.generated.yml"
	fi
done
