name: 'Setup Pkl'
description: 'Setup Pkl by installing, downloading, and adding it to the path.'
author: 'Pkl Community'

branding:
  icon: 'star'
  color: 'green'

inputs:
  pkl-version:
    description: The Pkl version to install.
    required: true
  github-token:
    description:
      A GitHub token to use for fetching the GitHub release asset from
      apple/pkl.
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
